"""Complete unified production schema

Revision ID: 836c756c6b73
Revises: 
Create Date: 2026-04-15 04:24:10.622510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '836c756c6b73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('flight_id', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('velocity', sa.BigInteger(), nullable=True),
    sa.Column('track', sa.Float(), nullable=True),
    sa.Column('dist_km', sa.Float(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('block_time', sa.BigInteger(), nullable=True),
    sa.Column('departure_hour', sa.DateTime(), nullable=True),
    sa.Column('arrival_hour', sa.DateTime(), nullable=True),
    sa.Column('business_pax', sa.BigInteger(), nullable=False),
    sa.Column('leisure_pax', sa.BigInteger(), nullable=False),
    sa.Column('passenger_count', sa.BigInteger(), nullable=False),
    sa.Column('pax_connection_count', sa.BigInteger(), nullable=False),
    sa.Column('load_factor', sa.Float(), nullable=True),
    sa.Column('revenue_tl', sa.BigInteger(), nullable=True),
    sa.Column('fuel_cost_tl', sa.Float(), nullable=True),
    sa.Column('co2_kg', sa.Float(), nullable=True),
    sa.Column('op_cost_tl', sa.BigInteger(), nullable=True),
    sa.Column('delay_cost_per_min', sa.BigInteger(), nullable=True),
    sa.Column('market_qsi_weight', sa.Float(), nullable=True),
    sa.Column('market_gap_index', sa.Float(), nullable=True),
    sa.Column('yield_quality_index', sa.Float(), nullable=True),
    sa.Column('aircraft_id', sa.String(length=20), nullable=False),
    sa.Column('ac_type', sa.String(length=20), nullable=True),
    sa.Column('ac_cat', sa.String(length=20), nullable=True),
    sa.Column('ac_range_km', sa.BigInteger(), nullable=True),
    sa.Column('ac_remaining_fh', sa.BigInteger(), nullable=True),
    sa.Column('ac_capacity', sa.BigInteger(), nullable=True),
    sa.Column('assigned_aircraft', sa.String(length=20), nullable=True),
    sa.Column('engine_health', sa.Float(), nullable=True),
    sa.Column('maintenance_reason', sa.Text(), nullable=True),
    sa.Column('crew_id', sa.String(length=20), nullable=True),
    sa.Column('crew_cert', sa.String(length=20), nullable=True),
    sa.Column('crew_base_fatigue', sa.BigInteger(), nullable=True),
    sa.Column('is_night_flight', sa.Boolean(), nullable=False),
    sa.Column('contrail_risk', sa.Float(), nullable=True),
    sa.Column('weather_risk', sa.Float(), nullable=True),
    sa.Column('tech_failure_prob', sa.Float(), nullable=True),
    sa.Column('causal_factor', sa.Text(), nullable=True),
    sa.Column('saf_usage', sa.Float(), nullable=True),
    sa.Column('gate_id', sa.String(length=10), nullable=True),
    sa.Column('pax_mobility_index', sa.Float(), nullable=True),
    sa.Column('ntn_link_active', sa.Boolean(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), nullable=False),
    sa.Column('assigned_delay', sa.BigInteger(), nullable=False),
    sa.Column('slot_pressure_flag', sa.Boolean(), nullable=False),
    sa.Column('decision_logic', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('user',
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('flights')
    # ### end Alembic commands ###
